baseurl = "https://kdas.me/"
languageCode = "en-us"
title = "Tech insights and tips"
theme = "casper"
paginate = 5
DisqusShortname = "kdas"
canonifyurls = true


[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  # cover = "media/cover.jpeg"
  description = "Sharing insights, tips, and solutions that I find useful in my professional journey"
  author = "Dmitry K."
  githubName = 'okdas'
  twitterName = 'kdasme'

[[menu.main]]
  name = "Notes"
  weight = -120
  identifier = "notes"
  url = "/"

[[menu.main]]
  name = "Links"
  weight = -110
  identifier = "links"
  url = "/links"
